# Generated by Django 5.1 on 2024-10-25 02:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HydroponicActions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LightStatus', models.BooleanField(null=True)),
                ('PumpStatus', models.BooleanField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HydroponicSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HydroponicParameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Temp', models.FloatField(null=True)),
                ('Humid', models.FloatField(null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('System', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sensors.hydroponicsystem')),
            ],
        ),
    ]
