# Generated by Django 5.1 on 2024-10-25 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hydroponicparameters',
            name='EC',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='hydroponicparameters',
            name='PH',
            field=models.FloatField(null=True),
        ),
    ]
