# Generated by Django 5.1 on 2024-11-16 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0002_hydroponicparameters_ec_hydroponicparameters_ph'),
    ]

    operations = [
        migrations.AddField(
            model_name='hydroponicparameters',
            name='Water_level',
            field=models.FloatField(null=True),
        ),
    ]
